(function () {
    'use strict';
    const grid = document.querySelector('[data-story-grid]');
    const detail = document.querySelector('[data-story-detail]');
    const filters = document.querySelector('[data-story-filters]');
    const count = document.querySelector('[data-story-count]');
    const search = document.querySelector('[data-story-search]');
    let activeCategory = 'All';
    function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, function (character) { return { '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]; }); }
    function filteredStories() { const term = search.value.trim().toLowerCase(); return historyStories.filter(function (story) { const matchesCategory = activeCategory === 'All' || story.category === activeCategory; const searchable = [story.title, story.teaser, story.description, story.category].concat(story.people, story.places).join(' ').toLowerCase(); return matchesCategory && searchable.indexOf(term) !== -1; }); }
    function bookReferenceMarkup(story) {
        if (!story.bookReferences || !story.bookReferences.length) return '';
        return '<div class="museum-book-references" aria-label="Book page references">' + story.bookReferences.map(function (pages) {
            const isRange = pages.indexOf('-') !== -1;
            const label = isRange ? 'pages ' + pages : 'page ' + pages;
            const target = HISTORY_BOOK_URL ? escapeHtml(HISTORY_BOOK_URL) + '#page=' + encodeURIComponent(pages.split('-')[0]) : '#history-book-page-' + encodeURIComponent(pages);
            return '<p class="museum-book-note" data-book-pages="' + escapeHtml(pages) + '"><a href="' + target + '">Read more from the book on ' + label + ' <span aria-hidden="true">&#8594;</span></a></p>';
        }).join('') + '</div>';
    }
    function renderDetail(story) {
        if (!story) { detail.hidden = true; detail.innerHTML = ''; return; }
        detail.hidden = false;
        const mediaContent = story.id === 'central-mosque'
            ? '<div class="museum-media-note"><i class="far fa-image" aria-hidden="true"></i><img src="img/mosques/demba-kunda-village-mosque-2017.web.jpg" alt="From Pavilion to Grand Mosque" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain;"></div>'
            : story.id === 'traditional-education'
                ? '<div class="museum-media-note" style="display:flex; flex-wrap:wrap; gap:.75rem; max-width:100%;"><img src="img/schools/traditional-school1.webp" alt="Traditional school study setting 1" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/traditional-school2.webp" alt="Traditional school study setting 2" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/traditional-school3.webp" alt="Traditional school study setting 3" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"></div>'
                : story.id === 'eight-villages-school'
                    ? '<div class="museum-media-note" style="display:flex; flex-wrap:wrap; gap:.75rem; max-width:100%;"><img src="img/schools/Al-Salafiya1.webp" alt="Al-Salafiya school image 1" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/Al-Salafiya2.webp" alt="Al-Salafiya school image 2" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/Al-Salafiya3.webp" alt="Al-Salafiya school image 3" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/Al-Salafiya4.webp" alt="Al-Salafiya school image 4" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/Al-Salafiya5.webp" alt="Al-Salafiya school image 5" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/Al-Salafiya6.webp" alt="Al-Salafiya school image 6" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"></div>'
                    : story.id === 'traditional-crafts'
                        ? '<div class="museum-media-note" style="display:flex; flex-wrap:wrap; gap:.75rem; max-width:100%;"><img src="img/NewD-workshops1.webp" alt="Traditional life workshop image 1" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain; flex:1 1 220px;"><img src="img/NewD-workshops2.webp" alt="Traditional life workshop image 2" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain; flex:1 1 220px;"><img src="img/NewD-workshops3.webp" alt="Traditional life workshop image 3" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain; flex:1 1 220px;"><img src="img/NewD-workshops4.webp" alt="Traditional life workshop image 4" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain; flex:1 1 220px;"><img src="img/NewD-workshops5.webp" alt="Traditional life workshop image 5" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain; flex:1 1 220px;"><img src="img/NewD-workshops6.webp" alt="Traditional life workshop image 6" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain; flex:1 1 220px;"></div>'
                        : story.id === 'water-project'
                            ? '<div class="museum-media-note" style="display:flex; flex-wrap:wrap; gap:.75rem; max-width:100%;"><img src="img/nwe-dembakunda-tanks1.webp" alt="Water project tank 1" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain; flex:1 1 220px;"><img src="img/nwe-dembakunda-tanks2.webp" alt="Water project tank 2" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain; flex:1 1 220px;"></div>'
                        : story.id === 'three-huts'
                            ? '<div class="museum-media-note"><i class="far fa-image" aria-hidden="true"></i><img src="img/huts.webp" alt="Three Huts, One Beginning" style="display:block; width:100%; max-width:100%; height:auto; object-fit:contain;"></div>'
                            : story.id === 'english-education'
                                ? '<div class="museum-media-note" style="display:flex; flex-wrap:wrap; gap:.75rem; max-width:100%;"><img src="img/schools/english-school1.webp" alt="English school image 1" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/english-school2.webp" alt="English school image 2" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/english-school3.webp" alt="English school image 3" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/english-school4.webp" alt="English school image 4" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/english-school5.webp" alt="English school image 5" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/english-school6.webp" alt="English school image 6" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"><img src="img/schools/english-school7.webp" alt="English school image 7" style="display:block; width:100%; max-width:100%; height:auto; object-fit:cover; flex:1 1 220px;"></div>'
                                : '<div class="museum-media-note"><i class="far fa-image" aria-hidden="true"></i><span>Historical photographs, video and audio are not yet documented for this record.</span></div>';
        detail.innerHTML = '<button class="museum-detail-close" type="button" data-close-story aria-label="Close story detail"><i class="fa fa-times" aria-hidden="true"></i></button><p class="museum-kicker">' + escapeHtml(story.category) + '</p><h2 id="story-detail-title">' + escapeHtml(story.title) + '</h2><p class="museum-period">' + escapeHtml(story.period) + '</p><p class="museum-detail-copy">' + escapeHtml(story.description) + '</p>' + bookReferenceMarkup(story) + '<div class="museum-detail-meta"><div><strong>Related people</strong><span>' + (story.people.length ? story.people.map(escapeHtml).join(', ') : 'Information not yet documented.') + '</span></div><div><strong>Related places</strong><span>' + (story.places.length ? story.places.map(escapeHtml).join(', ') : 'Information not yet documented.') + '</span></div><div><strong>Source</strong><span>' + escapeHtml(story.source) + '</span></div></div>' + mediaContent + (HISTORY_BOOK_URL ? '<a class="btn btn-primary" href="' + escapeHtml(HISTORY_BOOK_URL) + '" target="_blank" rel="noopener noreferrer">Read the history book <i class="fa fa-external-link-alt ms-2" aria-hidden="true"></i></a>' : '');
        detail.querySelector('[data-close-story]').addEventListener('click', function () { renderDetail(); });
        detail.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
    }
    function renderStories() {
        const stories = filteredStories(); count.textContent = stories.length + ' record' + (stories.length === 1 ? '' : 's');
        grid.innerHTML = stories.map(function (story) { return '<article class="museum-story-card"><div class="museum-story-card-top"><p class="museum-kicker">' + escapeHtml(story.category) + '</p><p class="museum-period">' + escapeHtml(story.period) + '</p></div><h2>' + escapeHtml(story.title) + '</h2><p>' + escapeHtml(story.teaser) + '</p><div class="museum-story-card-footer"><span>' + escapeHtml(story.source) + '</span><button type="button" data-story-id="' + escapeHtml(story.id) + '">Read the full story <i class="fa fa-arrow-right" aria-hidden="true"></i></button></div></article>'; }).join('') || '<p class="museum-empty">No archival records match this search.</p>';
        grid.querySelectorAll('[data-story-id]').forEach(function (button) { button.addEventListener('click', function () { renderDetail(historyStories.find(function (story) { return story.id === button.dataset.storyId; })); }); });
    }
    filters.addEventListener('click', function (event) { const button = event.target.closest('[data-category]'); if (!button) return; activeCategory = button.dataset.category; filters.querySelectorAll('button').forEach(function (item) { item.classList.toggle('is-active', item === button); item.setAttribute('aria-pressed', item === button ? 'true' : 'false'); }); renderStories(); });
    search.addEventListener('input', renderStories);
    renderStories();
    const requestedStoryId = new URLSearchParams(window.location.search).get('story');
    if (requestedStoryId) renderDetail(historyStories.find(function (story) { return story.id === requestedStoryId; }));
}());